import os
import uuid
import subprocess
from pathlib import Path

# The directory where uploaded user scripts and .sub files will live
JOBS_DIR = Path("C:/condor/jobs")

def setup_directories():
    JOBS_DIR.mkdir(parents=True, exist_ok=True)

def submit_script(script_content: bytes, original_filename: str, cpu: int = 1, ram: int = 512, require_gpu: bool = False, container_image: str = "none") -> str:
    """
    Saves the user's python script, writes an HTCondor .sub file, 
    and invokes condor_submit natively.
    """
    setup_directories()
    
    # Generate a unique job ID
    job_id = str(uuid.uuid4())[:8]
    job_folder = JOBS_DIR / job_id
    job_folder.mkdir(parents=True, exist_ok=True)
    
    # Save the user's python simulation script
    script_path = job_folder / original_filename
    with open(script_path, "wb") as f:
        f.write(script_content)
        
    # Generate the HTCondor submit file (.sub)
    sub_path = job_folder / "job.sub"
    
    # Base configuration
    sub_content = f"""
# HTCondor Submit File generated by SaaS Portal
arguments = {original_filename}

# Setup the environment and transfer files automatically
initialdir = {job_folder.as_posix()}
transfer_input_files = {original_filename}
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Output logs
output = job.out
error = job.err
log = job.log

# Request resources based on the script (hardcoded for MVP)
request_cpus = {cpu}
request_memory = {ram}MB
request_disk = 1GB
"""
    
    # Docker or Vanilla Python
    if container_image != "none":
        sub_content += f"\nuniverse = docker\ndocker_image = {container_image}\n"
    else:
        sub_content += f"\nexecutable = python\n"
        
    # GPU Request
    if require_gpu:
        sub_content += f"request_gpus = 1\n"
        
    sub_content += "\nqueue 1\n"
    
    with open(sub_path, "w") as f:
        f.write(sub_content.strip())
        
    # Execute condor_submit via subprocess
    try:
        result = subprocess.run(
            ["condor_submit", "job.sub"], 
            cwd=job_folder, 
            capture_output=True, 
            text=True, 
            check=True
        )
        return job_id
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Failed to submit HTCondor job: {e.stderr}")
    except FileNotFoundError:
        # Mock successful submission if condor_submit is not installed on dev machine
        return f"mock_{job_id}"

def get_job_status() -> list:
    """
    Queries HTCondor queue to retrieve job statuses.
    """
    try:
        result = subprocess.run(
            ["condor_q", "-json"], 
            capture_output=True, 
            text=True, 
            check=True
        )
        import json
        jobs = json.loads(result.stdout)
        
        status_map = {1: "Idle", 2: "Running", 3: "Removed", 4: "Completed", 5: "Held"}
        
        formatted_jobs = []
        for job in jobs:
            formatted_jobs.append({
                "cluster_id": job.get("ClusterId"),
                "status": status_map.get(job.get("JobStatus"), "Unknown"),
                "owner": job.get("Owner", "Student"),
                "cmd": job.get("Cmd", "")
            })
        return formatted_jobs
    except Exception:
        return [
            {"cluster_id": "mock_100", "status": "Running", "owner": "student@college.edu", "cmd": "fluid_sim.py"},
            {"cluster_id": "mock_101", "status": "Idle", "owner": "student@college.edu", "cmd": "ai_training.py"},
        ]

def cancel_job(job_id: str):
    try:
        subprocess.run(
            ["condor_rm", job_id], 
            capture_output=True, 
            text=True, 
            check=True
        )
    except Exception:
        pass

def get_job_logs(job_id: str) -> dict:
    job_folder = JOBS_DIR / job_id
    out_path = job_folder / "job.out"
    err_path = job_folder / "job.err"
    
    out_content = out_path.read_text() if out_path.exists() else "No stdout generated yet."
    err_content = err_path.read_text() if err_path.exists() else "No stderr generated yet."
    
    return {"stdout": out_content[-5000:], "stderr": err_content[-5000:]}

import shutil
def zip_job_output(job_id: str) -> str:
    """Zips the job directory and returns the path to the zip file."""
    job_folder = JOBS_DIR / job_id
    if not job_folder.exists():
        raise FileNotFoundError(f"Job {job_id} not found.")
        
    zip_path = JOBS_DIR / f"{job_id}_results"
    shutil.make_archive(zip_path.as_posix(), 'zip', job_folder.as_posix())
    return f"{zip_path.as_posix()}.zip"

def submit_pipeline(dag_json: dict) -> str:
    """
    Parses a simple pipeline JSON and writes a .dag file for HTCondor DAGMan.
    Format: {"nodes": ["A", "B", "C"], "edges": [{"from": "A", "to": "B"}]}
    """
    setup_directories()
    job_id = "dag_" + str(uuid.uuid4())[:6]
    job_folder = JOBS_DIR / job_id
    job_folder.mkdir(parents=True, exist_ok=True)
    
    dag_path = job_folder / "pipeline.dag"
    dag_content = ""
    
    # Generate generic .sub for nodes
    sub_path = job_folder / "node.sub"
    with open(sub_path, "w") as f:
        f.write("executable = python\narguments = $(script_name)\nqueue 1\n")
        
    for node in dag_json.get("nodes", []):
        dag_content += f"JOB {node} node.sub\n"
        dag_content += f'VARS {node} script_name="{node}.py"\n'
        
    for edge in dag_json.get("edges", []):
        dag_content += f"PARENT {edge['from']} CHILD {edge['to']}\n"
        
    with open(dag_path, "w") as f:
        f.write(dag_content)
        
    try:
        subprocess.run(["condor_submit_dag", "pipeline.dag"], cwd=job_folder, capture_output=True, check=True)
        return job_id
    except Exception:
        return f"mock_{job_id}"
