package config

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"text/template"
)

// Generator builds dynamic HTCondor configuration based on hardware and policy
type Generator struct {
	poolHost   string
	policyName string
	installDir string
}

func NewGenerator(poolHost, policyName, installDir string) *Generator {
	return &Generator{
		poolHost:   poolHost,
		policyName: policyName,
		installDir: installDir,
	}
}

// ConfigTemplate defines the cycle-scavenging rules exactly as required
const ConfigTemplate = `
# ====================================================================
# DYNAMIC HTCONDOR EXECUTE NODE CONFIGURATION
# Generated by execute-node-agent
# ====================================================================

# -----------------------------
# 1. Daemon Selection
# -----------------------------
# Only start the Master and Startd (Execute) daemons
DAEMON_LIST = MASTER, STARTD

# -----------------------------
# 2. Idle Detection (Cycle Scavenging Logic)
# -----------------------------
{{if eq .Policy "strict-idle"}}
# Strict Idle Policy:
# 1. No keyboard/mouse activity for 15 minutes (900 seconds)
# 2. CPU load is below 0.3 (30%)
MachineIsIdle = (KeyboardIdle > 900) && (LoadAvg < 0.3)

# Define when to start accepting jobs
START = $(MachineIsIdle)

# Define when to immediately pause (suspend) a running grid job
# If the physical user touches the keyboard, suspend within 1 second.
SUSPEND = (KeyboardIdle < 1) 

# If the user stays active for more than 10 minutes, kill the grid job completely
# and requeue it to another machine in the campus grid.
PREEMPT = (KeyboardIdle < 1) && (StateTimer > 600)
{{else}}
# Relaxed/Custom policy could go here
MachineIsIdle = True
START = True
SUSPEND = False
PREEMPT = False
{{end}}

# -----------------------------
# 3. Central Manager Binding
# -----------------------------
# Your hosted central manager (running condor_collector and condor_negotiator)
CONDOR_HOST = {{.PoolHost}}

# Use IDTOKENS for security so you don't have to manage complex SSL certificates on local labs
SEC_DEFAULT_AUTHENTICATION_METHODS = IDTOKENS
SEC_CLIENT_AUTHENTICATION_METHODS = IDTOKENS

# Tell condor where to find the IDTOKEN we saved
SEC_TOKEN_DIRECTORY = $(LOCAL_DIR)/tokens.d

# Disable all legacy GSI/SSL configs just to be safe
SEC_DEFAULT_ENCRYPTION = REQUIRED
SEC_DEFAULT_INTEGRITY = REQUIRED

# -----------------------------
# 4. Networking and Ports (Optional but recommended)
# -----------------------------
# If strict campus firewalls exist, we might need CCB (Condor Connection Broker)
# CCB_ADDRESS = $(CONDOR_HOST)
`

// TemplateData holds the variables for the config template
type TemplateData struct {
	PoolHost string
	Policy   string
}

// Generate writes the condor_config file to the installation directory
func (g *Generator) Generate() error {
	configDir := filepath.Join(g.installDir, "etc")
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	configPath := filepath.Join(configDir, "condor_config")
	log.Printf("Generating condor configuration at %s", configPath)

	file, err := os.OpenFile(configPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0644)
	if err != nil {
		return fmt.Errorf("failed to open config file: %w", err)
	}
	defer file.Close()

	tmpl, err := template.New("condor_config").Parse(ConfigTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	data := TemplateData{
		PoolHost: g.poolHost,
		Policy:   g.policyName,
	}

	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	log.Println("HTCondor configuration successfully generated.")
	
	// Set the environment variable so the daemon knows where its config is
	os.Setenv("CONDOR_CONFIG", configPath)
	return nil
}
